version: '3'
services:
  front:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - 3002:3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules/
      - /usr/src/app/.next/
